export const IS_AUTH = "IS_AUTH";
export const HANDLE_LANGUAGE_CHANGE = "HANDLE_LANGUAGE_CHANGE";
export const FETCH_INSTITUTIONS_FAILURE = "FETCH_INSTITUTIONS_FAILURE";
export const FETCH_INSTITUTIONS_SUCCESS = "FETCH_INSTITUTIONS_SUCCESS";
export const CREATE_INSTITUTION_FAILURE = "CREATE_INSTITUTION_FAILURE";
export const CREATE_INSTITUTION_SUCCESS = "CREATE_INSTITUTION_SUCCESS";
export const CREATE_INSTITUTION_REQUEST = "CREATE_INSTITUTION_REQUEST";
export const FETCH_INSTITUTIONS_REQUEST = "FETCH_INSTITUTIONS_REQUEST";
export const DELETE_INSTITUTION_FAILURE= "DELETE_INSTITUTION_FAILURE";
export const DELETE_INSTITUTION_SUCCESS= "DELETE_INSTITUTION_SUCCESS";
export const DELETE_INSTITUTION_REQUEST= "DELETE_INSTITUTION_REQUEST";
export  const FETCH_NOTIFICATIONS_FAILURE= "FETCH_NOTIFICATIONS_FAILURE";
export  const FETCH_NOTIFICATIONS_SUCCESS= "FETCH_NOTIFICATIONS_SUCCESS";
export  const FETCH_NOTIFICATIONS_REQUEST= "FETCH_NOTIFICATIONS_REQUEST";
export  const READ_NOTIFICATION_FAILURE= "READ_NOTIFICATION_FAILURE";
export  const READ_NOTIFICATION_SUCCESS= "READ_NOTIFICATION_SUCCESS";
export  const READ_NOTIFICATION_REQUEST= "READ_NOTIFICATION_REQUEST";
export const FETCH_USER_PROFILE_REQUEST= "FETCH_USER_PROFILE_REQUEST";
export const FETCH_USER_PROFILE_SUCCESS= "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILURE= "FETCH_USER_PROFILE_FAILURE";
export const LOGOUT= "LOGOUT";
export const CHANGE_USER_PASSWORD_FAILURE= "CHANGE_USER_PASSWORD_FAILURE";
export const CHANGE_USER_PASSWORD_SUCCESS= "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_REQUEST= "CHANGE_USER_PASSWORD_REQUEST";
export const FETCH_USERS_FAILURE= "FETCH_USERS_FAILURE";
export const FETCH_USERS_SUCCESS= "FETCH_USERS_SUCCESS";
export const FETCH_USERS_REQUEST= "FETCH_USERS_REQUEST";
export const UPDATE_USER_PROFILE_FAILURE= "UPDATE_USER_PROFILE_FAILURE";
export const UPDATE_USER_PROFILE_SUCCESS= "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_REQUEST= "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_STATUS_REQUEST = 'UPDATE_USER_STATUS_REQUEST';
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS';
export const UPDATE_USER_STATUS_FAILURE = 'UPDATE_USER_STATUS_FAILURE';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

export const FETCH_PROGRAMS_SUCCESS = 'FETCH_PROGRAMS_SUCCESS';
export const FETCH_PROGRAMS_REQUEST = 'FETCH_PROGRAMS_REQUEST';
export const FETCH_PROGRAMS_FAILURE = 'FETCH_PROGRAMS_FAILURE';
export const CREATE_PROGRAM_REQUEST = 'CREATE_PROGRAM_REQUEST';
export const CREATE_PROGRAM_SUCCESS = 'CREATE_PROGRAM_SUCCESS';
export const CREATE_PROGRAM_FAILURE = 'CREATE_PROGRAM_FAILURE';
export const UPDATE_PROGRAM_REQUEST = 'UPDATE_PROGRAM_REQUEST';
export const UPDATE_PROGRAM_SUCCESS = 'UPDATE_PROGRAM_SUCCESS';
export const UPDATE_PROGRAM_FAILURE = 'UPDATE_PROGRAM_FAILURE';
export const DELETE_PROGRAM_REQUEST = 'DELETE_PROGRAM_REQUEST';
export const DELETE_PROGRAM_SUCCESS = 'DELETE_PROGRAM_SUCCESS';
export const DELETE_PROGRAM_FAILURE = 'DELETE_PROGRAM_FAILURE';

export const CREATE_SEMESTER_FAILURE = 'CREATE_SEMESTER_FAILURE';
export const CREATE_SEMESTER_SUCCESS = 'CREATE_SEMESTER_SUCCESS';
export const CREATE_SEMESTER_REQUEST = 'CREATE_SEMESTER_REQUEST';
export const UPDATE_SEMESTER_FAILURE = 'UPDATE_SEMESTER_FAILURE';
export const UPDATE_SEMESTER_SUCCESS = 'UPDATE_SEMESTER_SUCCESS';
export const UPDATE_SEMESTER_REQUEST = 'UPDATE_SEMESTER_REQUEST';
export const DELETE_SEMESTER_FAILURE = 'DELETE_SEMESTER_FAILURE';
export const DELETE_SEMESTER_SUCCESS = 'DELETE_SEMESTER_SUCCESS';
export const DELETE_SEMESTER_REQUEST = 'DELETE_SEMESTER_REQUEST';
export const FETCH_SEMESTERS_SUCCESS = 'FETCH_SEMESTERS_SUCCESS';
export const FETCH_SEMESTERS_REQUEST = 'FETCH_SEMESTERS_REQUEST';
export const FETCH_SEMESTERS_FAILURE = 'FETCH_SEMESTERS_FAILURE';

export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const CREATE_CLASS_FAILURE = 'CREATE_CLASS_FAILURE';
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const UPDATE_CLASS_FAILURE = 'UPDATE_CLASS_FAILURE';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST';
export const DELETE_CLASS_FAILURE = 'DELETE_CLASS_FAILURE';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE';
export const FETCH_INSTRUCTORS_SUCCESS = 'FETCH_INSTRUCTORS_SUCCESS';
export const FETCH_INSTRUCTORS_FAILURE = 'FETCH_INSTRUCTORS_FAILURE';

// Take Attendance
export const TAKE_ATTENDANCE_REQUEST = 'TAKE_ATTENDANCE_REQUEST';
export const TAKE_ATTENDANCE_SUCCESS = 'TAKE_ATTENDANCE_SUCCESS';
export const TAKE_ATTENDANCE_FAILURE = 'TAKE_ATTENDANCE_FAILURE';

// Update Attendance
export const UPDATE_ATTENDANCE_REQUEST = 'UPDATE_ATTENDANCE_REQUEST';
export const UPDATE_ATTENDANCE_SUCCESS = 'UPDATE_ATTENDANCE_SUCCESS';
export const UPDATE_ATTENDANCE_FAILURE = 'UPDATE_ATTENDANCE_FAILURE';

// Fetch Attendance History
export const FETCH_ATTENDANCE_HISTORY_REQUEST = 'FETCH_ATTENDANCE_HISTORY_REQUEST';
export const FETCH_ATTENDANCE_HISTORY_SUCCESS = 'FETCH_ATTENDANCE_HISTORY_SUCCESS';
export const FETCH_ATTENDANCE_HISTORY_FAILURE = 'FETCH_ATTENDANCE_HISTORY_FAILURE';

// Student Attendance Stats
export const FETCH_ATTENDANCE_STATS_REQUEST = 'FETCH_ATTENDANCE_STATS_REQUEST';
export const FETCH_ATTENDANCE_STATS_SUCCESS = 'FETCH_ATTENDANCE_STATS_SUCCESS';
export const FETCH_ATTENDANCE_STATS_FAILURE = 'FETCH_ATTENDANCE_STATS_FAILURE';

// Bulk Update Attendance
export const BULK_UPDATE_ATTENDANCE_REQUEST = 'BULK_UPDATE_ATTENDANCE_REQUEST';
export const BULK_UPDATE_ATTENDANCE_SUCCESS = 'BULK_UPDATE_ATTENDANCE_SUCCESS';
export const BULK_UPDATE_ATTENDANCE_FAILURE = 'BULK_UPDATE_ATTENDANCE_FAILURE';

export const FETCH_ATTENDANCE_BY_DATE_FAILURE= "FETCH_ATTENDANCE_BY_DATE_FAILURE";
export const FETCH_ATTENDANCE_BY_DATE_SUCCESS= "FETCH_ATTENDANCE_BY_DATE_SUCCESS";
export const FETCH_ATTENDANCE_BY_DATE_REQUEST= "FETCH_ATTENDANCE_BY_DATE_REQUEST";


export const FETCH_ENROLLED_STUDENTS_REQUEST = 'FETCH_ENROLLED_STUDENTS_REQUEST';
export const FETCH_ENROLLED_STUDENTS_SUCCESS = 'FETCH_ENROLLED_STUDENTS_SUCCESS';
export const FETCH_ENROLLED_STUDENTS_FAILURE = 'FETCH_ENROLLED_STUDENTS_FAILURE';

export const ENROLL_STUDENTS_REQUEST = 'ENROLL_STUDENTS_REQUEST';
export const ENROLL_STUDENTS_SUCCESS = 'ENROLL_STUDENTS_SUCCESS';
export const ENROLL_STUDENTS_FAILURE = 'ENROLL_STUDENTS_FAILURE';

export const UNENROLL_STUDENT_REQUEST = 'UNENROLL_STUDENT_REQUEST';
export const UNENROLL_STUDENT_SUCCESS = 'UNENROLL_STUDENT_SUCCESS';
export const UNENROLL_STUDENT_FAILURE = 'UNENROLL_STUDENT_FAILURE';

export const FETCH_INSTITUTION_USER_FAILURE = 'FETCH_INSTITUTION_USER_FAILURE';
export const FETCH_INSTITUTION_USER_SUCCESS = 'FETCH_INSTITUTION_USER_SUCCESS';
export const FETCH_INSTITUTION_USER_REQUEST = 'FETCH_INSTITUTION_USER_REQUEST';

export const FETCH_CLASS_ENROLLED_STUDENTS_REQUEST = 'FETCH_CLASS_ENROLLED_STUDENTS_REQUEST';
export const FETCH_CLASS_ENROLLED_STUDENTS_SUCCESS = 'FETCH_CLASS_ENROLLED_STUDENTS_SUCCESS';
export const FETCH_CLASS_ENROLLED_STUDENTS_FAILURE = 'FETCH_CLASS_ENROLLED_STUDENTS_FAILURE';

export const FETCH_PROGRAM_ENROLLED_STUDENTS_REQUEST = 'FETCH_PROGRAM_ENROLLED_STUDENTS_REQUEST';
export const FETCH_PROGRAM_ENROLLED_STUDENTS_SUCCESS = 'FETCH_PROGRAM_ENROLLED_STUDENTS_SUCCESS';
export const FETCH_PROGRAM_ENROLLED_STUDENTS_FAILURE = 'FETCH_PROGRAM_ENROLLED_STUDENTS_FAILURE';

export const ENROLL_CLASS_STUDENTS_FAILURE='ENROLL_CLASS_STUDENTS_FAILURE';
export const ENROLL_CLASS_STUDENTS_SUCCESS='ENROLL_CLASS_STUDENTS_SUCCESS';
export const ENROLL_CLASS_STUDENTS_REQUEST='ENROLL_CLASS_STUDENTS_REQUEST';

export const UNENROLL_CLASS_STUDENT_FAILURE='UNENROLL_CLASS_STUDENT_FAILURE';
export const UNENROLL_CLASS_STUDENT_SUCCESS='UNENROLL_CLASS_STUDENT_SUCCESS';
export const UNENROLL_CLASS_STUDENT_REQUEST='UNENROLL_CLASS_STUDENT_REQUEST';

export const FETCH_INSTRUCTOR_CLASSES_REQUEST = 'FETCH_INSTRUCTOR_CLASSES_REQUEST';
export const FETCH_INSTRUCTOR_CLASSES_SUCCESS = 'FETCH_INSTRUCTOR_CLASSES_SUCCESS';
export const FETCH_INSTRUCTOR_CLASSES_FAILURE = 'FETCH_INSTRUCTOR_CLASSES_FAILURE';

export const FETCH_CLASS_STUDENTS_REQUEST = 'FETCH_CLASS_STUDENTS_REQUEST';
export const FETCH_CLASS_STUDENTS_SUCCESS = 'FETCH_CLASS_STUDENTS_SUCCESS';
export const FETCH_CLASS_STUDENTS_FAILURE = 'FETCH_CLASS_STUDENTS_FAILURE';

