export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_WATCH_LIST = "GET_WATCH_LIST";
export const ADD_TO_WATCH_LIST = "ADD_TO_WATCH_LIST";
export const DELETE_WATCH_LIST = "DELETE_WATCH_LIST";
export const IS_AUTH = "IS_AUTH";
export const HANDLE_LANGUAGE_CHANGE = "HANDLE_LANGUAGE_CHANGE";
